# <backspace>+<escape>+<enter>
# sudo cp ~/utono/rpd/etc/keyd/default.conf /root/utono/rpd/etc/keyd
# keyd reload

[ids]
*

[aliases]
iso-level3-shift = shift
leftshift = shift
rightshift = shift
leftcontrol = control
rightcontrol = control
leftalt = alt
rightalt = alt

[main]

# Toggle for enabling or disabling home row mods
f5 = toggle(home_row_mods)

capslock = overload(meta, esc)

# Default key behavior (when home row mods are inactive)
a = a
s = s
d = d
f = f
j = j
k = k
l = l
; = ;

# Home Row Modifiers - Activated when the 'home_row_mods' layer is toggled
[home_row_mods]
a = lettermod(shift, a, 100, 200)
s = lettermod(meta, s, 100, 200)
d = lettermod(alt, d, 100, 200)
f = lettermod(control, f, 100, 200)

j = lettermod(control, j, 100, 200)
k = lettermod(alt, k, 100, 200)
l = lettermod(meta, l, 100, 200)
; = lettermod(shift, ;, 100, 200)

leftcontrol = layer(unbind)
rightcontrol = layer(unbind)
iso-level3-shift = layer(unbind)
leftshift = layer(unbind)
rightshift = layer(unbind)
leftalt = layer(unbind)

[unbind]
