# sudo cp ~/utono/rpd/etc/keyd/default.conf /root/utono/rpd/etc/keyd
# keyd reload
#
# github.com: path:keyd/default.conf
# <backspace>+<escape>+<enter>

[ids]
*
# must reboot after adding / removing a device
# 0fac:0ade:efba1ddf

[main]

# f+j = esc

# Maps capslock to escape when pressed and control when held.
capslock = overload(meta, esc)

s = lettermod(meta, s, 100, 200)
d = lettermod(alt, d, 100, 200)
f = lettermod(control, f, 100, 200)
# f = lettermod(shift, f, 100, 200)

# j = lettermod(shift, j, 100, 200)
j = lettermod(control, j, 100, 200)
k = lettermod(alt, k, 100, 200)
l = lettermod(meta, l, 100, 200)
# ; = lettermod(meta, ;, 100, 200)

# The proposed main layer implements one of the variants of home row modifers. Notice we
# use the one-shot-shift pattern, which is important to prevent shifting errors caused by
# the necessary delay with which characters are emitted under overloadt (on release,
# instead of on press).

# leftshift = oneshot(shift)
# rightshift = oneshot(shift)

[meta]

leftcontrol = layer(unbind)         # Disable Left Control (LCTRL)
rightcontrol = layer(unbind)         # Disable Left Control (LCTRL)
# iso-level3-shift = layer(unbind)
# leftshift = layer(unbind)        # Disable Left Shift (LSHIFT)
# rightshift = layer(unbind)        # Disable Left Shift (LSHIFT)
leftalt = layer(unbind)          # Disable Left Alt (LALT)
rightalt = layer(unbind)

[unbind]

# must reboot after setting these modifiers = noop
# iso-level3-shift = noop
# leftcontrol = noop         # Disable Left Control (LCTRL)
# rightcontrol = noop         # Disable Left Control (LCTRL)
# leftshift = noop        # Disable Left Shift (LSHIFT)
# rightshift = noop        # Disable Left Shift (LSHIFT)
# leftalt = noop          # Disable Left Alt (LALT)
# rightalt = noop

