# sudo systemctll enable keyd && sudo systemctl start keyd

[ids]

*

[main]

# Maps capslock to escape when pressed and control when held.
capslock = overload(meta, esc)

# Remaps the escape key to capslock
# esc = capslock
